// src/lib/views/rules/inspector/PortInspector.svelte
<script lang="ts">
  import Icon from '$lib/components/Icon.svelte';
  import { Badge } from '$lib/components/ui/badge/index.js';
  import { Button } from '$lib/components/ui/button/index.js';
  import { Separator } from '$lib/components/ui/separator/index.js';
  import {
    uiHandleForSemantic,
    type FlowHandleDirection,
  } from '$lib/rules/native-authoring/flow-adapter';
  import type { FlowNode } from '$lib/rules/native-authoring/wire';
  import { NODE_KIND_META } from '../nodes/meta';
  import { getNodePorts, type InputPortDef, type OutputPortDef } from '../nodes/ports';
  import type { FlowViewEdge } from '../nodes/types';

  type Props = {
    nodeId: string | null;
    node: FlowNode | null;
    direction: FlowHandleDirection | null;
    handle: string | null;
    edges: FlowViewEdge[];
    onEditNode: () => void;
  };

  let { nodeId, node, direction, handle, edges, onEditNode }: Props = $props();

  const uiHandle = $derived.by(() => {
    if (!node || !direction || !handle) return null;
    return uiHandleForSemantic(node.config.kind, node.config.value, handle, direction);
  });
  const port = $derived.by((): InputPortDef | OutputPortDef | null => {
    if (!node || !direction || !uiHandle) return null;
    const ports = getNodePorts(node.config.kind, node.config.value);
    return direction === 'source'
      ? (ports.outputs.find((candidate) => candidate.id === uiHandle) ?? null)
      : (ports.inputs.find((candidate) => candidate.id === uiHandle) ?? null);
  });
  const relatedEdges = $derived(
    nodeId && direction && handle
      ? edges.filter((edge) =>
          direction === 'source'
            ? edge.data.edge.from.node_id === nodeId && edge.data.edge.from.handle === handle
            : edge.data.edge.to.node_id === nodeId && edge.data.edge.to.handle === handle,
        )
      : [],
  );
  const typeLabel = $derived(
    port ? ('accepts' in port ? port.accepts.join(' / ') : port.emits) : 'unknown',
  );
  const role = $derived(port?.role ?? 'data');
</script>

{#if !node || !nodeId || !direction || !handle || !port}
  <div class="flex min-h-40 items-center justify-center px-4">
    <p class="text-center text-sm text-ink-muted">选择一个端口查看其连接合同</p>
  </div>
{:else}
  <div class="flex flex-col gap-3">
    <div class="flex items-start gap-2 px-1">
      <span
        class="flex size-7 shrink-0 items-center justify-center rounded-md bg-lantern-soft text-lantern-strong"
      >
        <Icon name={direction === 'source' ? 'arrow-right' : 'arrow-left'} class="size-4" />
      </span>
      <div class="min-w-0">
        <p class="text-xs font-semibold text-ink">端口属性</p>
        <code class="block truncate text-[10px] text-ink-muted">{nodeId}</code>
      </div>
    </div>

    <Separator />

    <section class="flex flex-col gap-2 px-1" aria-labelledby="port-identity-title">
      <h3 id="port-identity-title" class="text-xs font-semibold text-ink">语义身份</h3>
      <dl class="grid grid-cols-[auto_minmax(0,1fr)] gap-x-3 gap-y-2 text-xs">
        <dt class="text-ink-muted">节点</dt>
        <dd class="truncate text-right text-ink">{NODE_KIND_META[node.config.kind].label}</dd>
        <dt class="text-ink-muted">方向</dt>
        <dd class="text-right text-ink">{direction === 'source' ? '输出' : '输入'}</dd>
        <dt class="text-ink-muted">显示句柄</dt>
        <dd class="truncate text-right font-mono text-ink">{uiHandle}</dd>
        <dt class="text-ink-muted">真实句柄</dt>
        <dd class="truncate text-right font-mono text-ink">{handle}</dd>
        <dt class="text-ink-muted">角色</dt>
        <dd class="text-right"><Badge variant="outline">{role}</Badge></dd>
        <dt class="text-ink-muted">数据类型</dt>
        <dd class="text-right font-mono text-ink">{typeLabel}</dd>
      </dl>
    </section>

    <section class="flex flex-col gap-2 px-1" aria-labelledby="port-connections-title">
      <div class="flex items-center justify-between gap-2">
        <h3 id="port-connections-title" class="text-xs font-semibold text-ink">连接</h3>
        <span class="font-mono text-[10px] text-ink-subtle">{relatedEdges.length}</span>
      </div>
      {#if relatedEdges.length === 0}
        <p class="text-[11px] leading-4 text-ink-subtle">
          尚未连接。拖动端口即可创建经过校验的连线。
        </p>
      {:else}
        <ul class="flex flex-col gap-1.5" aria-label="端口连接列表">
          {#each relatedEdges as edge (edge.id)}
            <li class="border-l-2 border-lantern-strong/50 pl-2">
              <code class="block truncate text-[10px] text-ink-muted">{edge.id}</code>
              <p class="text-[11px] text-ink">
                {direction === 'source'
                  ? `${edge.data.edge.to.node_id} · ${edge.data.edge.to.handle}`
                  : `${edge.data.edge.from.node_id} · ${edge.data.edge.from.handle}`}
              </p>
            </li>
          {/each}
        </ul>
      {/if}
    </section>

    <Button type="button" variant="outline" class="w-full" onclick={onEditNode}>
      <Icon name="pencil-simple" class="size-3.5" />
      <span>编辑节点配置</span>
    </Button>
  </div>
{/if}

// src/features/rules/inspector/PortInspector.tsx
//! 端口检查器：端口的连接合同与已有连接。
//!
//! 显示句柄与真实句柄要分开列：merge/condition 的 UI handle 是按下标生成的，
//! 与 definition 里的语义 handle 不是同一个字符串，排查连线问题时必须都能看到。

import { Icon } from '@/components/Icon';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { useMessages } from '@/shared/i18n/messages';
import type { FlowNode } from '@/shared/tauri/rules';
import { uiHandleForSemantic, type FlowViewEdge } from '../model/flow-adapter';
import { getNodePorts, type InputPortDef, type OutputPortDef } from '../model/ports';
import { nodeKindLabel } from '../labels';
import { useRuleEditorSessionStore } from '../use-session';

const PORT_TYPE_SEPARATOR = ' / ';

export function PortInspector({
  node,
  direction,
  handle,
  edges,
}: {
  node: FlowNode;
  direction: 'source' | 'target';
  handle: string;
  edges: readonly FlowViewEdge[];
}) {
  const m = useMessages();
  const store = useRuleEditorSessionStore();

  const uiHandle = uiHandleForSemantic(node.config.kind, node.config.value, handle, direction);
  const ports = getNodePorts(node.config.kind, node.config.value);
  const port: InputPortDef | OutputPortDef | undefined =
    direction === 'source'
      ? ports.outputs.find((candidate) => candidate.id === uiHandle)
      : ports.inputs.find((candidate) => candidate.id === uiHandle);

  const related = edges.filter((edge) =>
    direction === 'source'
      ? edge.data.edge.from.node_id === node.id && edge.data.edge.from.handle === handle
      : edge.data.edge.to.node_id === node.id && edge.data.edge.to.handle === handle,
  );

  const typeLabel = port
    ? 'accepts' in port
      ? port.accepts.join(PORT_TYPE_SEPARATOR)
      : port.emits
    : '—';

  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-start gap-2">
        <span className="flex size-7 shrink-0 items-center justify-center bg-lantern-soft text-lantern-strong">
          <Icon name={direction === 'source' ? 'arrow-right' : 'arrow-left'} />
        </span>
        <div className="min-w-0">
          <p className="text-ui-sm font-semibold text-ink">{m.rules_port_inspector_title()}</p>
          <code className="block truncate font-mono text-[10px] text-ink-muted">{node.id}</code>
        </div>
      </div>

      <Separator />

      <dl className="grid grid-cols-[auto_minmax(0,1fr)] items-center gap-x-3 gap-y-2 text-ui-sm">
        <dt className="text-ink-muted">{m.rules_port_inspector_node()}</dt>
        <dd className="truncate text-right text-ink">{nodeKindLabel(m, node.config.kind)}</dd>
        <dt className="text-ink-muted">{m.rules_port_inspector_direction()}</dt>
        <dd className="text-right text-ink">
          {direction === 'source'
            ? m.rules_port_inspector_direction_output()
            : m.rules_port_inspector_direction_input()}
        </dd>
        <dt className="text-ink-muted">{m.rules_port_inspector_ui_handle()}</dt>
        <dd className="truncate text-right font-mono text-ink">{uiHandle}</dd>
        <dt className="text-ink-muted">{m.rules_port_inspector_semantic_handle()}</dt>
        <dd className="truncate text-right font-mono text-ink">{handle}</dd>
        <dt className="text-ink-muted">{m.rules_port_inspector_role()}</dt>
        <dd className="text-right">
          <Badge variant="outline">{port?.role ?? 'data'}</Badge>
        </dd>
        <dt className="text-ink-muted">{m.rules_edge_value_kind()}</dt>
        <dd className="truncate text-right font-mono text-ink">{typeLabel}</dd>
      </dl>

      <section className="flex flex-col gap-1.5">
        <div className="flex items-center justify-between gap-2">
          <h3 className="text-ui-sm font-semibold text-ink">
            {m.rules_port_inspector_connections()}
          </h3>
          <span className="font-mono text-[10px] text-ink-subtle">{related.length}</span>
        </div>
        {related.length === 0 ? (
          <p className="text-ui-sm leading-4 text-ink-subtle">
            {m.rules_port_inspector_no_connections()}
          </p>
        ) : (
          <ul
            className="flex flex-col gap-1.5"
            aria-label={m.rules_port_inspector_connection_list()}
          >
            {related.map((edge) => {
              const peer = direction === 'source' ? edge.data.edge.to : edge.data.edge.from;
              return (
                <li key={edge.id} className="border-l-2 border-lantern-strong/50 pl-2">
                  <code className="block truncate font-mono text-[10px] text-ink-muted">
                    {edge.id}
                  </code>
                  <p className="truncate text-ui-sm text-ink">
                    {peer.node_id} · {peer.handle}
                  </p>
                </li>
              );
            })}
          </ul>
        )}
      </section>

      <Button
        variant="outline"
        size="sm"
        className="w-full"
        onClick={() => store.getState().selectNode(node.id)}
      >
        <Icon name="pencil-simple" />
        <span>{m.rules_port_inspector_edit_node()}</span>
      </Button>
    </div>
  );
}
