// src/features/library/LibraryHome.tsx
import { useCallback, useEffect, useMemo, useState, useSyncExternalStore } from 'react';
import { Icon } from '@/components/Icon';
import { PageToolbar } from '@/components/PageToolbar';
import { Button } from '@/components/ui/button';
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from '@/components/ui/empty';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useMessages } from '@/shared/i18n/messages';
import type { LibraryEntry } from '@/shared/tauri/library';
import { LibraryInspector } from './LibraryInspector';
import { createLibraryWorkflow } from './workflow';

type LibraryTab = 'all' | 'favorites';

interface LibraryHomeProps {
  initialResourceId?: string;
  onInspectorClose?: () => void;
}

function progressLabel(entry: LibraryEntry, recorded: string, empty: string): string {
  if (!entry.progress) return empty;
  if (entry.progress.total === null) return `${recorded} ${entry.progress.position}`;
  return `${entry.progress.position}/${entry.progress.total}`;
}

function progressRatio(entry: LibraryEntry): number | null {
  if (!entry.progress || entry.progress.total === null || entry.progress.total <= 0) return null;
  return Math.min(1, entry.progress.position / entry.progress.total);
}

export function LibraryHome({ initialResourceId, onInspectorClose }: LibraryHomeProps) {
  const m = useMessages();
  const workflow = useMemo(() => createLibraryWorkflow(), []);
  const state = useSyncExternalStore(workflow.subscribe, workflow.getState, workflow.getState);
  const [query, setQuery] = useState('');
  const [tab, setTab] = useState<LibraryTab>('all');
  const [selectedResourceId, setSelectedResourceId] = useState<string | null>(
    initialResourceId ?? null,
  );

  useEffect(() => {
    void workflow.refresh();
  }, [workflow]);

  useEffect(() => {
    if (initialResourceId) setSelectedResourceId(initialResourceId);
  }, [initialResourceId]);

  const { rows } = state;
  const visibleRows = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return rows.filter(({ entry, media }) => {
      if (tab === 'favorites' && !entry.favorite) return false;
      if (!needle) return true;
      return [entry.resource_id, media?.title ?? '', media?.creator ?? ''].some((value) =>
        value.toLowerCase().includes(needle),
      );
    });
  }, [query, rows, tab]);

  const selectedRow = rows.find((row) => row.entry.resource_id === selectedResourceId);
  const selectedFailure = selectedResourceId ? state.failures[selectedResourceId] : undefined;
  const selectedPending = selectedResourceId
    ? state.pendingResourceIds.includes(selectedResourceId)
    : false;

  const closeInspector = useCallback(
    (open: boolean) => {
      if (open) return;
      setSelectedResourceId(null);
      onInspectorClose?.();
    },
    [onInspectorClose],
  );

  const toggleFavorite = useCallback(
    (entry: LibraryEntry) => {
      void workflow.updateOwnership(
        entry.resource_id,
        !entry.favorite,
        entry.favorite ? false : entry.pinned,
      );
    },
    [workflow],
  );

  const togglePinned = useCallback(
    (entry: LibraryEntry) => {
      void workflow.updateOwnership(
        entry.resource_id,
        entry.favorite || !entry.pinned,
        !entry.pinned,
      );
    },
    [workflow],
  );

  return (
    <>
      <PageToolbar
        meta={m.library_item_count({ count: visibleRows.length })}
        actions={
          <Button
            variant="ghost"
            size="icon-sm"
            aria-label={m.library_refresh()}
            title={m.library_refresh()}
            disabled={state.kind === 'loading'}
            onClick={() => void workflow.refresh()}
          >
            <Icon name="arrow-clockwise" className="text-base" />
          </Button>
        }
      >
        <Tabs
          value={tab}
          onValueChange={(value) => {
            if (value === 'all' || value === 'favorites') setTab(value);
          }}
        >
          <TabsList>
            <TabsTrigger value="all">{m.library_tab_all()}</TabsTrigger>
            <TabsTrigger value="favorites">{m.library_tab_favorites()}</TabsTrigger>
          </TabsList>
        </Tabs>
        <div className="ml-auto max-w-xs min-w-0 flex-1 sm:ml-2 sm:flex-none">
          <Input
            type="search"
            autoComplete="off"
            aria-label={m.library_search_label()}
            placeholder={m.library_search_placeholder()}
            value={query}
            onChange={(event) => setQuery(event.target.value)}
          />
        </div>
      </PageToolbar>

      <div className="px-(--page-gutter) py-(--density-section-gap)">
        {state.kind === 'loading' && rows.length === 0 ? (
          <div className="flex flex-col gap-px">
            {[0, 1, 2, 3, 4].map((index) => (
              <Skeleton key={index} className="h-(--density-row) w-full" />
            ))}
          </div>
        ) : null}

        {state.kind === 'error' ? (
          <div role="alert" className="border border-hairline p-3">
            <p className="font-medium">{m.library_load_error()}</p>
            <p className="mt-1 font-mono text-ui-sm wrap-break-word text-ink-muted">
              {state.detail}
            </p>
            <Button
              variant="outline"
              size="sm"
              className="mt-3"
              onClick={() => void workflow.refresh()}
            >
              {m.action_retry()}
            </Button>
          </div>
        ) : null}

        {state.kind === 'ready' && visibleRows.length === 0 ? (
          <Empty className="border border-dashed border-hairline">
            <EmptyHeader>
              <EmptyMedia variant="icon">
                <Icon name="books" className="text-base" />
              </EmptyMedia>
              <EmptyTitle>{m.library_empty_title()}</EmptyTitle>
              <EmptyDescription>
                {query || tab === 'favorites'
                  ? m.library_empty_filtered()
                  : m.library_empty_unfiltered()}
              </EmptyDescription>
            </EmptyHeader>
          </Empty>
        ) : null}

        {visibleRows.length > 0 ? (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>{m.library_col_resource()}</TableHead>
                <TableHead>{m.library_inspector_media()}</TableHead>
                <TableHead className="w-32">{m.library_col_progress()}</TableHead>
                <TableHead className="w-44">{m.library_col_opened()}</TableHead>
                <TableHead className="w-20 text-right">{m.library_favorite()}</TableHead>
                <TableHead className="w-20 text-right">{m.library_pinned()}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {visibleRows.map(({ entry, media }) => {
                const ratio = progressRatio(entry);
                const pending = state.pendingResourceIds.includes(entry.resource_id);
                const failure = state.failures[entry.resource_id];
                return (
                  <TableRow key={entry.resource_id}>
                    <TableCell className="max-w-0">
                      <button
                        type="button"
                        className="block max-w-full truncate text-left font-mono hover:underline focus-visible:outline-1 focus-visible:outline-ring"
                        onClick={() => setSelectedResourceId(entry.resource_id)}
                      >
                        {entry.resource_id}
                      </button>
                      {failure ? (
                        <span
                          className="flex items-center gap-1 text-ui-sm text-danger"
                          role="alert"
                        >
                          <Icon name="warning-circle" />
                          <span className="truncate">
                            {m.library_update_error({ detail: failure })}
                          </span>
                        </span>
                      ) : null}
                    </TableCell>
                    <TableCell className="max-w-0">
                      {media ? (
                        <div className="min-w-0">
                          <p className="truncate">{media.title}</p>
                          <p className="truncate text-ui-sm text-ink-muted">{media.creator}</p>
                        </div>
                      ) : (
                        <span className="text-ink-muted">{m.library_media_missing()}</span>
                      )}
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <span className="w-16 shrink-0 font-mono text-ink-muted tabular-nums">
                          {progressLabel(
                            entry,
                            m.library_progress_recorded(),
                            m.library_value_none(),
                          )}
                        </span>
                        {ratio === null ? null : (
                          <span className="h-0.5 min-w-0 flex-1 bg-surface-3">
                            <span
                              className="block h-full bg-lantern-strong"
                              style={{ width: `${ratio * 100}%` }}
                            />
                          </span>
                        )}
                      </div>
                    </TableCell>
                    <TableCell className="text-ink-muted">
                      {entry.last_opened_at ?? m.library_value_none()}
                    </TableCell>
                    <TableCell className="text-right">
                      <Button
                        variant="ghost"
                        size="icon-sm"
                        aria-label={entry.favorite ? m.library_unfavorite() : m.library_favorite()}
                        title={entry.favorite ? m.library_unfavorite() : m.library_favorite()}
                        disabled={pending}
                        onClick={() => toggleFavorite(entry)}
                      >
                        <Icon name={entry.favorite ? 'star-fill' : 'star'} className="text-base" />
                      </Button>
                    </TableCell>
                    <TableCell className="text-right">
                      <Button
                        variant="ghost"
                        size="icon-sm"
                        aria-label={entry.pinned ? m.library_unpin() : m.library_pin()}
                        title={entry.pinned ? m.library_unpin() : m.library_pin()}
                        disabled={pending}
                        onClick={() => togglePinned(entry)}
                      >
                        <Icon
                          name={entry.pinned ? 'push-pin-fill' : 'push-pin'}
                          className="text-base"
                        />
                      </Button>
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        ) : null}
      </div>

      <LibraryInspector
        open={selectedResourceId !== null}
        row={selectedRow}
        pending={selectedPending}
        failure={selectedFailure}
        onOpenChange={closeInspector}
        onFavoriteChange={() => {
          if (selectedRow) toggleFavorite(selectedRow.entry);
        }}
        onPinnedChange={() => {
          if (selectedRow) togglePinned(selectedRow.entry);
        }}
      />
    </>
  );
}

// src/lib/views/library/LibraryHome.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { SvelteSet } from 'svelte/reactivity';
  import Icon from '$lib/components/Icon.svelte';
  import { resolve } from '$app/paths';
  import PageHeader from '$lib/components/PageHeader.svelte';
  import { m } from '$lib/i18n';
  import {
    loadLibraryProjection,
    updateLibraryEntry,
    type LibraryUpdateReceipt,
  } from './library-api';
  import {
    projectLibrary,
    type LibraryEntry,
    type LibraryProjectionResponse,
  } from './library-projection';

  type Props = {
    projection?: LibraryProjectionResponse | null;
    load?: () => Promise<LibraryProjectionResponse>;
    update?: (entry: LibraryEntry) => Promise<LibraryUpdateReceipt>;
  };

  type LibraryViewState =
    | { kind: 'loading' }
    | { kind: 'load-error' }
    | { kind: 'empty'; projection: LibraryProjectionResponse }
    | { kind: 'ready'; projection: LibraryProjectionResponse };

  let {
    projection = null,
    load = loadLibraryProjection,
    update = updateLibraryEntry,
  }: Props = $props();

  function stateFromProjection(next: LibraryProjectionResponse): LibraryViewState {
    return projectLibrary(next).length === 0
      ? { kind: 'empty', projection: next }
      : { kind: 'ready', projection: next };
  }

  let viewState = $derived<LibraryViewState>(
    projection ? stateFromProjection(projection) : { kind: 'loading' },
  );
  let updateError = $state(false);
  let pendingResourceIds = new SvelteSet<string>();
  const items = $derived(viewState.kind === 'ready' ? projectLibrary(viewState.projection) : []);

  onMount(() => {
    if (!projection) void loadProjection();
  });

  async function loadProjection(): Promise<void> {
    viewState = { kind: 'loading' };
    try {
      viewState = stateFromProjection(await load());
    } catch {
      viewState = { kind: 'load-error' };
    }
  }

  async function toggleState(resourceId: string, key: 'favorite' | 'pinned'): Promise<void> {
    if (pendingResourceIds.has(resourceId)) return;

    const item = items.find((candidate) => candidate.resource_id === resourceId);
    if (!item) return;

    const nextEntry: LibraryEntry = {
      ...item.state,
      [key]: !item.state[key],
    };

    updateError = false;
    pendingResourceIds.add(resourceId);
    try {
      const receipt = await update(nextEntry);
      if (viewState.kind !== 'ready') return;

      const nextProjection: LibraryProjectionResponse = {
        ...viewState.projection,
        global_seq: receipt.global_seq,
        entries: viewState.projection.entries.map((entry) =>
          entry.resource_id === resourceId
            ? {
                ...nextEntry,
                revision: receipt.revision,
                updated_global_seq: receipt.global_seq,
              }
            : entry,
        ),
      };
      viewState = stateFromProjection(nextProjection);
      updateError = false;
    } catch {
      updateError = true;
    } finally {
      pendingResourceIds.delete(resourceId);
    }
  }
</script>

<section class="mx-auto flex w-full max-w-6xl flex-col gap-6">
  <PageHeader title={m.library_title()} />

  {#if viewState.kind === 'loading'}
    <p class="flex min-h-48 items-center gap-3 text-sm text-ink-muted" role="status">
      <Icon name="database" class="size-5" />
      <span>{m.library_loading()}</span>
    </p>
  {:else if viewState.kind === 'load-error'}
    <div class="border-danger/35 bg-danger/10 rounded-xl border px-5 py-5" role="alert">
      <p class="text-danger text-sm font-medium">{m.library_load_error()}</p>
      <button
        type="button"
        class="glass-control mt-4 inline-flex min-h-11 items-center gap-2 rounded-lg border border-hairline-strong px-4 text-sm font-semibold text-ink outline-none hover:bg-surface-2 focus-visible:shadow-[var(--focus-ring)]"
        onclick={loadProjection}
      >
        <Icon name="arrow-clockwise" class="size-4" />
        <span>{m.library_retry()}</span>
      </button>
    </div>
  {:else if viewState.kind === 'ready'}
    <ul
      class="glass-panel divide-y divide-hairline rounded-xl border border-hairline"
      aria-label={m.library_title()}
    >
      {#each items as entry (entry.resource_id)}
        <li>
          <article
            class="grid gap-3 px-4 py-3 md:grid-cols-[minmax(0,1fr)_auto]"
            data-resource-id={entry.resource_id}
          >
            <div class="min-w-0">
              <h2 class="truncate text-sm font-semibold text-ink">{entry.resource_id}</h2>
              {#if entry.state.progress}
                <p class="mt-1 text-xs text-ink-subtle">
                  {entry.state.progress.position}{#if entry.state.progress.total !== null}
                    / {entry.state.progress.total}
                  {/if}
                </p>
              {/if}
              <p class="mt-1 text-xs text-ink-subtle">
                {m.library_revision({ revision: entry.state.revision })}
              </p>
            </div>
            <div
              class="flex items-start gap-1"
              role="group"
              aria-label={entry.resource_id}
              aria-busy={pendingResourceIds.has(entry.resource_id)}
            >
              <button
                type="button"
                class="glass-control grid h-11 w-11 place-items-center rounded-md border border-hairline text-ink-muted outline-none hover:bg-lantern-soft hover:text-ink focus-visible:shadow-[var(--focus-ring)] disabled:cursor-wait disabled:opacity-60"
                aria-label={entry.state.favorite ? m.library_unfavorite() : m.library_favorite()}
                aria-pressed={entry.state.favorite}
                aria-busy={pendingResourceIds.has(entry.resource_id)}
                disabled={pendingResourceIds.has(entry.resource_id)}
                onclick={() => toggleState(entry.resource_id, 'favorite')}
              >
                <Icon name={entry.state.favorite ? 'star-fill' : 'star'} class="size-4" />
              </button>
              <button
                type="button"
                class="glass-control grid h-11 w-11 place-items-center rounded-md border border-hairline text-ink-muted outline-none hover:bg-lantern-soft hover:text-ink focus-visible:shadow-[var(--focus-ring)] disabled:cursor-wait disabled:opacity-60"
                aria-label={entry.state.pinned ? m.library_unpin() : m.library_pin()}
                aria-pressed={entry.state.pinned}
                aria-busy={pendingResourceIds.has(entry.resource_id)}
                disabled={pendingResourceIds.has(entry.resource_id)}
                onclick={() => toggleState(entry.resource_id, 'pinned')}
              >
                <Icon name={entry.state.pinned ? 'push-pin-fill' : 'push-pin'} class="size-4" />
              </button>
            </div>
          </article>
        </li>
      {/each}
    </ul>
  {:else}
    <div
      class="glass-panel rounded-xl border border-hairline px-5 py-5"
      role="status"
      data-testid="library-empty"
    >
      <h2 class="text-sm font-semibold text-ink">{m.library_empty_title()}</h2>
      <a
        href={resolve('/sources' as '/')}
        class="glass-control mt-4 inline-flex min-h-11 items-center gap-2 rounded-lg border border-hairline-strong px-4 text-sm font-semibold text-ink outline-none hover:bg-surface-2 focus-visible:shadow-[var(--focus-ring)]"
      >
        <Icon name="arrow-right" class="size-4" />
        <span>{m.action_manage_sources()}</span>
      </a>
    </div>
  {/if}

  {#if updateError}
    <p class="text-danger text-sm" role="alert">{m.library_update_error()}</p>
  {/if}
</section>
