// src/lib/views/rules/diagnostics/DiagnosticList.svelte
<script lang="ts">
  import { getLocale, m } from '$lib/i18n';
  import Icon from '$lib/components/Icon.svelte';
  import { Badge } from '$lib/components/ui/badge/index.js';
  import { ScrollArea } from '$lib/components/ui/scroll-area/index.js';
  import type { ValidationState } from '$lib/rules/native-authoring/core';
  import type { InstallDiagnostic } from '$lib/rules/native-authoring/wire';
  import type { NativeRuleEditorSession } from '$lib/rules/native-authoring/session.svelte';

  type Props = {
    session: NativeRuleEditorSession;
  };

  let { session }: Props = $props();

  function localizedMessage(key: string, fallback: { en: string; 'zh-CN': string }): string {
    const candidate = (m as unknown as Record<string, () => string>)[key];
    if (typeof candidate === 'function') return candidate();
    if (getLocale() === 'en') return fallback.en;
    return fallback['zh-CN'];
  }

  const diagnostics = $derived(session.diagnostics);
  const validation = $derived<ValidationState>(
    session.validation ?? {
      status: 'unknown',
      revision: null,
      definitionHash: null,
      planHash: null,
      diagnostics: [],
    },
  );

  /** severity 排序权重 */
  function severityOrder(sev: InstallDiagnostic['severity']): number {
    return sev === 'error' ? 0 : sev === 'warning' ? 1 : 2;
  }

  function severityLabel(sev: InstallDiagnostic['severity']): string {
    return sev === 'error'
      ? m.rules_diagnostics_error({ count: 0 })
      : sev === 'warning'
        ? m.rules_diagnostics_warning({ count: 0 })
        : m.rules_diagnostics_info({ count: 0 });
  }

  function severityIcon(sev: InstallDiagnostic['severity']): 'warning-circle' | 'file-text' {
    return sev === 'error' || sev === 'warning' ? 'warning-circle' : 'file-text';
  }

  function severityBadgeVariant(
    sev: InstallDiagnostic['severity'],
  ): 'destructive' | 'default' | 'outline' {
    return sev === 'error' ? 'destructive' : sev === 'warning' ? 'default' : 'outline';
  }

  /** severity 图标颜色（Icon 组件不接受 class: 指令，用计算字符串）。 */
  function severityIconClass(sev: InstallDiagnostic['severity']): string {
    return sev === 'error'
      ? 'text-destructive'
      : sev === 'warning'
        ? 'text-warning'
        : 'text-ink-muted';
  }

  function validationLabel(status: typeof validation.status): string {
    const labels = {
      unknown: ['rules_validation_unknown', 'Not validated', '未校验'],
      pending: ['rules_validation_pending', 'Validating', '校验中'],
      valid: ['rules_validation_valid', 'Validated', '已通过'],
      invalid: ['rules_validation_invalid', 'Validation failed', '未通过'],
      stale: ['rules_validation_stale', 'Validation is stale', '结果已过期'],
      error: ['rules_validation_error', 'Validation error', '校验失败'],
    } as const;
    const [key, en, zhCN] = labels[status];
    return localizedMessage(key, { en, 'zh-CN': zhCN });
  }

  function focusDiagnostic(diagnostic: InstallDiagnostic): void {
    const path = diagnostic.span?.path;
    const nodeId = path?.match(/^\/flow\/nodes\/([^/]+)/)?.[1];
    if (nodeId && session.definition.flow.nodes.some((node) => node.id === nodeId)) {
      session.selectNode(nodeId);
      return;
    }
    const edge = session.flowProjection.edges.find((candidate) => {
      const semantic = candidate.data.edge;
      return Boolean(path?.includes(semantic.from.node_id) && path?.includes(semantic.to.node_id));
    });
    if (edge) session.selectEdge(edge.id);
  }
</script>

<div class="flex flex-col gap-2">
  <div class="flex items-center gap-2">
    <h3 class="flex items-center gap-2 text-sm font-medium">
      <Icon name="warning-circle" class="size-4 text-lantern-strong" />
      <span>{m.rules_diagnostics()}</span>
      {#if diagnostics.length > 0}
        <Badge variant="outline">{diagnostics.length}</Badge>
      {/if}
    </h3>
    <Badge variant={validation.status === 'valid' ? 'default' : 'outline'} class="ml-auto">
      {validationLabel(validation.status)}
    </Badge>
  </div>

  {#if diagnostics.length === 0}
    <p class="text-xs text-ink-muted">{m.rules_diagnostics_empty()}</p>
  {:else}
    <ScrollArea class="max-h-80">
      <div class="flex flex-col gap-1">
        {#each [...diagnostics].sort((a, b) => severityOrder(a.severity) - severityOrder(b.severity)) as diag (diag.code + diag.severity + (diag.span?.start ?? 0))}
          <button
            type="button"
            class="flex w-full items-start gap-2 rounded-md px-2 py-1.5 text-left text-xs transition-colors hover:bg-surface-2"
            aria-label={diag.code}
            onclick={() => focusDiagnostic(diag)}
          >
            <Icon
              name={severityIcon(diag.severity)}
              class="mt-0.5 size-3 shrink-0 {severityIconClass(diag.severity)}"
            />
            <div class="min-w-0 flex-1">
              <div class="flex items-center gap-1">
                <Badge variant={severityBadgeVariant(diag.severity)} class="text-[10px]">
                  {diag.code}
                </Badge>
                <span class="text-ink-muted">{severityLabel(diag.severity)}</span>
              </div>
              <p class="mt-0.5 leading-snug text-ink">{diag.message}</p>
              {#if diag.span}
                <p class="text-ink-muted">
                  {diag.span.path ?? ''}:{diag.span.start}–{diag.span.end}
                </p>
              {/if}
            </div>
          </button>
        {/each}
      </div>
    </ScrollArea>
  {/if}
</div>

// src/features/rules/DiagnosticList.tsx
//! 诊断栏：校验状态 + 当前诊断列表。
//!
//! 诊断是 compiler 的稳定 code + 已本地化 message（Rust 侧给出），
//! 这里只负责排序、分级配色与点击定位。

import { useMemo } from 'react';
import { Icon } from '@/components/Icon';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/shared/utils';
import { useMessages } from '@/shared/i18n/messages';
import type { InstallDiagnostic } from '@/shared/tauri/rules';
import type { ValidationState } from './model/core';
import { useRuleEditorSession, useRuleEditorSessionStore } from './use-session';

type Severity = InstallDiagnostic['severity'];

/** 错误在前、警告其次、提示最后。 */
const SEVERITY_ORDER: Record<Severity, number> = { error: 0, warning: 1, info: 2 };

function severityClass(severity: Severity): string {
  return severity === 'error'
    ? 'text-danger'
    : severity === 'warning'
      ? 'text-warning'
      : 'text-ink-muted';
}

/** 诊断没有稳定 id，用 code + span + message 合成；完全一致的两条本就是同一件事。 */
function diagnosticKey(diagnostic: InstallDiagnostic): string {
  const { span } = diagnostic;
  return `${diagnostic.code}@${span?.path ?? ''}:${span?.start ?? ''}:${diagnostic.message}`;
}

function statusLabel(m: ReturnType<typeof useMessages>, status: ValidationState['status']) {
  switch (status) {
    case 'unknown': {
      return m.rules_validation_unknown();
    }
    case 'pending': {
      return m.rules_validation_pending();
    }
    case 'valid': {
      return m.rules_validation_valid();
    }
    case 'invalid': {
      return m.rules_validation_invalid();
    }
    case 'stale': {
      return m.rules_validation_stale();
    }
    case 'error': {
      return m.rules_validation_error();
    }
  }
}

export function DiagnosticList() {
  const m = useMessages();
  const store = useRuleEditorSessionStore();
  const validation = useRuleEditorSession((state) => state.core.validation);

  const sorted = useMemo(
    () =>
      [...validation.diagnostics].sort(
        (left, right) => SEVERITY_ORDER[left.severity] - SEVERITY_ORDER[right.severity],
      ),
    [validation.diagnostics],
  );

  const counts = useMemo(() => {
    const result = { error: 0, warning: 0, info: 0 };
    for (const diagnostic of validation.diagnostics) result[diagnostic.severity] += 1;
    return result;
  }, [validation.diagnostics]);

  return (
    <section
      aria-label={m.rules_diagnostics()}
      className="flex max-h-52 shrink-0 flex-col border-t border-hairline bg-surface-1"
    >
      <header className="flex h-(--density-row) shrink-0 items-center gap-2 border-b border-hairline px-(--page-gutter)">
        <h2 className="font-medium">{m.rules_diagnostics()}</h2>
        <Badge variant={validation.status === 'valid' ? 'secondary' : 'outline'}>
          {statusLabel(m, validation.status)}
        </Badge>
        {counts.error > 0 ? (
          <span className="text-ui-sm text-danger">
            {m.rules_diagnostics_error({ count: counts.error })}
          </span>
        ) : null}
        {counts.warning > 0 ? (
          <span className="text-ui-sm text-warning">
            {m.rules_diagnostics_warning({ count: counts.warning })}
          </span>
        ) : null}
        {typeof validation.revision === 'number' ? (
          <span className="ml-auto shrink-0 font-mono text-ui-sm text-ink-subtle">
            rev {validation.revision}
          </span>
        ) : null}
      </header>

      {sorted.length === 0 ? (
        <p className="px-(--page-gutter) py-2 text-ui-sm text-ink-subtle">
          {m.rules_diagnostics_empty()}
        </p>
      ) : (
        <ul className="min-h-0 flex-1 overflow-y-auto">
          {sorted.map((diagnostic) => (
            <li key={diagnosticKey(diagnostic)}>
              <button
                type="button"
                className="flex w-full items-start gap-2 px-(--page-gutter) py-1.5 text-left text-ui-sm hover:bg-surface-2 focus-visible:bg-surface-2 focus-visible:outline-none"
                onClick={() => {
                  // 诊断的 span.path 目前对应节点 id，用于把画布焦点带过去。
                  const nodeId = diagnostic.span?.path;
                  if (nodeId) store.getState().selectNode(nodeId);
                }}
              >
                <Icon
                  name={diagnostic.severity === 'info' ? 'file-text' : 'warning-circle'}
                  className={cn('mt-0.5 shrink-0', severityClass(diagnostic.severity))}
                />
                <span className="min-w-0 flex-1">{diagnostic.message}</span>
                <span className="shrink-0 font-mono text-[10px] text-ink-subtle">
                  {diagnostic.code}
                </span>
              </button>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
