// src/lib/views/rules/RuleFlowCanvas.svelte
<script lang="ts">
  //! 规则流程图画布：Svelte Flow 受控容器。
  //!
  //! nodes/edges 全部来自 session.flowProjection（adapter 投影），画布不持有 core；
  //! onconnect/onreconnect/onnodeschange 经连接 gate 校验后发 typed action 到 session。
  //! 校验失败返回 false / 不派发，绝不写入无效 semantic state。

  import {
    Background,
    Controls,
    ViewportPortal,
    SvelteFlow,
    type Connection,
    type IsValidConnection,
    type ConnectionLineType,
  } from '@xyflow/svelte';
  import { onMount } from 'svelte';
  import '@xyflow/svelte/dist/style.css';
  import { m } from '$lib/i18n';
  import { cn } from '$lib/utils.js';
  import type { NativeRuleEditorSession } from '$lib/rules/native-authoring/session.svelte';
  import type { StandardIntent } from '$lib/rules/native-authoring/wire';
  import {
    layoutNativeRuleFlow,
    type FlowNodeDimensions,
  } from '$lib/rules/native-authoring/flow-layout';
  import {
    parseEditorSelection,
    semanticHandleForUi,
    type FlowHandleDirection,
  } from '$lib/rules/native-authoring/flow-adapter';
  import {
    type ConnectionRejectReason,
    flowEntryByIntentFromDefinition,
    semanticEdgeFromConnection,
    validateConnection,
  } from './connection-gate';
  import FlowTopBar from './FlowTopBar.svelte';
  import NodePalette from './NodePalette.svelte';
  import LoopRegionOverlay from './LoopRegionOverlay.svelte';
  import ViewportSync from './ViewportSync.svelte';
  import SemanticEdge from './SemanticEdge.svelte';
  import { nodeTypes } from './nodes';
  import type { FlowViewEdge, FlowViewNode } from './nodes/types';

  type Props = {
    session: NativeRuleEditorSession;
    class?: string;
  };

  let { session, class: className }: Props = $props();

  const SMOOTH_STEP_CONNECTION_LINE = 'smoothstep' as ConnectionLineType;
  const CANVAS_ARIA_LABELS = {
    'controls.ariaLabel': m.rules_canvas_controls(),
    'controls.zoomIn.ariaLabel': m.rules_canvas_zoom_in(),
    'controls.zoomOut.ariaLabel': m.rules_canvas_zoom_out(),
    'controls.fitView.ariaLabel': m.rules_canvas_fit_view(),
    'controls.interactive.ariaLabel': m.rules_canvas_interactive(),
  };

  // ---- 投影（adapter 派生，响应式） ----
  const viewNodes = $derived.by(() =>
    session.flowProjection.nodes.map((node) => ({
      ...node,
      data: {
        ...node.data,
        onPortSelect: (direction: FlowHandleDirection, handle: string) =>
          handlePortSelect(node.id, direction, handle),
      },
    })),
  );
  const nodeIds = $derived(viewNodes.map((node) => node.id));
  const viewEdges = $derived(
    session.flowProjection.edges.map((edge) => ({
      ...edge,
      type: 'semantic',
      class: cn('flow-edge', `flow-edge-${edge.data.role}`, edge.data.dimmed && 'flow-edge-dimmed'),
    })),
  );
  const loopRegions = $derived(session.flowProjection.loopRegions ?? []);
  const loopRegionViews = $derived.by(() =>
    loopRegions.map((region) => ({ region, bounds: regionBounds(region) })),
  );
  const intentFocus = $derived(session.intentFocus);
  const semanticEdges = $derived(viewEdges.map((edge) => edge.data.edge));
  const entryByIntent = $derived(flowEntryByIntentFromDefinition(session.definition));
  const focusEntry = $derived(intentFocus ? (entryByIntent[intentFocus] ?? null) : null);

  // ---- 连接 gate：随投影变化重建 ----
  const gateGraph = $derived({
    nodes: viewNodes.map((node) => ({
      id: node.id,
      kind: node.data.kind,
      config: node.data.config,
    })),
    edges: semanticEdges,
    focusEntry,
  });

  const gate = $derived.by(
    () => (connection: Connection) => validateConnection(connection, gateGraph).ok,
  );

  const connectionReasonText: Record<ConnectionRejectReason, string> = {
    'missing-handle': '连接缺少端口。',
    'unknown-node': '连接节点已不存在。',
    'unknown-handle': '端口已失效，请重新选择。',
    'self-loop': '节点不能连接自身。',
    'incompatible-ports': '端口数据类型不兼容。',
    'duplicate-edge': '这条连接已经存在。',
    'entry-occupied': '入口只能保留一条连接。',
    'back-edge': '普通回路不允许连接。',
    'loop-yield-occupied': 'Loop yield 只能保留一条回边。',
    'intent-mismatch': '连接不属于当前意图子图。',
  };

  function checkConnection(connection: Connection, graph = gateGraph): boolean {
    const verdict = validateConnection(connection, graph);
    connectionRejectReason = verdict.ok ? null : verdict.reason;
    return verdict.ok;
  }

  /** onconnect：gate 通过才派发 typed action。 */
  function handleConnect(connection: Connection) {
    if (!checkConnection(connection)) return;
    session.connect(toSemanticEdge(connection));
  }

  async function handleAutoLayout(dimensions: FlowNodeDimensions): Promise<void> {
    const positions = await layoutNativeRuleFlow(session.definition, dimensions);
    session.layoutNodes(positions);
  }

  function handlePortSelect(
    nodeId: string,
    direction: FlowHandleDirection,
    uiHandle: string,
  ): void {
    const node = session.flowProjection.nodes.find((candidate) => candidate.id === nodeId);
    if (!node) return;
    session.selectPort(
      nodeId,
      direction,
      semanticHandleForUi(node.data.kind, node.data.config, uiHandle, direction),
    );
  }

  /** onbeforeconnect：不兼容返回 false，不写无效 semantic state。 */
  function handleBeforeConnect(connection: Connection): Connection | false {
    return checkConnection(connection) ? connection : false;
  }

  /** onreconnect：校验时排除正在替换的旧边，避免原位置误判 duplicate。 */
  function handleReconnect(oldEdge: FlowViewEdge, connection: Connection) {
    const reconnectGraph = { ...gateGraph, excludeEdgeId: oldEdge.id };
    if (!checkConnection(connection, reconnectGraph)) return;
    session.reconnect(oldEdge.data.edge, toSemanticEdge(connection));
  }

  function toSemanticEdge(connection: Connection) {
    const sourceNode = gateGraph.nodes.find((node) => node.id === connection.source);
    const targetNode = gateGraph.nodes.find((node) => node.id === connection.target);
    return semanticEdgeFromConnection(connection, sourceNode, targetNode);
  }

  /** onnodedragstop：拖动结束 → 发 moveNode。 */
  function handleNodeDragStop(event: {
    targetNode: FlowViewNode | null;
    nodes: FlowViewNode[];
    event: MouseEvent | TouchEvent;
  }) {
    const node = event.targetNode ?? event.nodes[0];
    if (!node) return;
    session.moveNode(node.id, {
      x: node.position.x,
      y: node.position.y,
    });
  }

  /** onnodeclick：选中节点。 */
  function handleNodeClick(event: { node: FlowViewNode; event: MouseEvent | TouchEvent }) {
    const target = event.event.target;
    if (target instanceof Element) {
      const portRow = target.closest<HTMLElement>('.flow-node-port-row');
      if (portRow) {
        const side = portRow.dataset.portSide;
        const handle = portRow.dataset.portId;
        if ((side === 'input' || side === 'output') && handle) {
          handlePortSelect(event.node.id, side === 'input' ? 'target' : 'source', handle);
          return;
        }
      }
    }
    session.selectNode(event.node.id);
  }

  /** onedgeclick：选中连线，Inspector 读取同一条 semantic edge。 */
  function handleEdgeClick(event: { edge: FlowViewEdge; event: MouseEvent }) {
    session.selectEdge(event.edge.id);
  }

  function handleSelectionChange(event: { nodes: FlowViewNode[]; edges: FlowViewEdge[] }) {
    const selectedEdge = event.edges[0];
    if (selectedEdge) {
      if (session.selection !== `edge:${selectedEdge.id}`) {
        session.selectEdge(selectedEdge.id);
      }
      return;
    }

    const selectedNode = event.nodes[0];
    const nextSelection = selectedNode?.id ?? null;
    if (session.selection !== nextSelection) {
      session.selectNode(nextSelection);
    }
  }

  /** onpaneclick：取消选中。 */
  function handlePaneClick() {
    session.selectNode(null);
  }

  type DeleteSelectionFacade = {
    disconnect: (edge: FlowViewEdge['data']['edge']) => void;
    deleteNode: (nodeId: string) => void;
    flowProjection: { edges: FlowViewEdge[] };
    [key: string]: unknown;
  };

  function deleteSelection(nodeIds: string[], edgeIds: string[]): void {
    const facade = session as unknown as DeleteSelectionFacade;
    const deletion = facade['deleteSelection'];
    if (typeof deletion === 'function') {
      deletion.call(facade, nodeIds, edgeIds);
      return;
    }
    for (const edgeId of edgeIds) {
      const edge = facade.flowProjection.edges.find((candidate) => candidate.id === edgeId);
      if (edge) facade.disconnect(edge.data.edge);
    }
    for (const nodeId of nodeIds) facade.deleteNode(nodeId);
  }

  /** ondelete：节点与连线使用一个 semantic transaction 删除。 */
  function handleDelete(event: { nodes: FlowViewNode[]; edges: FlowViewEdge[] }) {
    deleteSelection(
      event.nodes.map((node) => node.id),
      event.edges.map((edge) => edge.id),
    );
  }

  // ---- 键盘删除：Backspace/Delete 删除选中节点（incident 边由 session 组合） ----
  // 外部监听挂载即订阅、卸载即 teardown；快捷键只作用于画布选择。
  onMount(() => {
    const onKey = (event: KeyboardEvent) => {
      const target = event.target;
      if (
        target instanceof HTMLElement &&
        (target.tagName === 'INPUT' ||
          target.tagName === 'TEXTAREA' ||
          target.tagName === 'SELECT' ||
          target.isContentEditable)
      ) {
        return;
      }
      const modifier = event.metaKey || event.ctrlKey;
      if (modifier && !event.altKey && event.key.toLowerCase() === 'z') {
        event.preventDefault();
        if (event.shiftKey) session.redo();
        else session.undo();
        return;
      }
      if (modifier && !event.altKey && event.key.toLowerCase() === 'y') {
        event.preventDefault();
        session.redo();
        return;
      }
      if ((event.key === 'Delete' || event.key === 'Backspace') && session.selection) {
        event.preventDefault();
        const selection = parseEditorSelection(session.selection);
        if (selection.kind === 'edge') {
          deleteSelection([], [selection.edgeId]);
        } else if (selection.kind === 'node') {
          deleteSelection([selection.nodeId], []);
        }
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  });

  // ---- palette 开关 ----
  let connectionRejectReason = $state<ConnectionRejectReason | null>(null);
  let paletteOpen = $state(false);
  let flowNodeMeasurementEpoch = $state(0);
  let flowRoot: HTMLElement | null = null;

  const NODE_WIDTH = 252;
  const NODE_HEIGHT = 142;
  const REGION_PADDING_X = 34;
  const REGION_PADDING_Y = 38;

  function observeFlowNodeDimensions(root: HTMLElement) {
    flowRoot = root;
    let disposed = false;
    let refreshQueued = false;
    const refresh = () => {
      if (disposed || refreshQueued) return;
      refreshQueued = true;
      queueMicrotask(() => {
        refreshQueued = false;
        if (!disposed) flowNodeMeasurementEpoch += 1;
      });
    };
    const resizeObserver =
      typeof ResizeObserver === 'undefined' ? undefined : new ResizeObserver(refresh);
    const observeNodes = () => {
      resizeObserver?.disconnect();
      root.querySelectorAll<HTMLElement>('.svelte-flow__node').forEach((node) => {
        resizeObserver?.observe(node);
      });
      refresh();
    };
    const mutationObserver =
      typeof MutationObserver === 'undefined' ? undefined : new MutationObserver(observeNodes);

    mutationObserver?.observe(root, { childList: true, subtree: true });
    observeNodes();

    return () => {
      disposed = true;
      refreshQueued = false;
      resizeObserver?.disconnect();
      mutationObserver?.disconnect();
      if (flowRoot === root) flowRoot = null;
    };
  }

  function nodeSize(nodeId: string): { width: number; height: number } {
    const fallback = { width: NODE_WIDTH, height: NODE_HEIGHT };
    if (!flowRoot || flowNodeMeasurementEpoch === 0) return fallback;
    const element = [...flowRoot.querySelectorAll<HTMLElement>('.svelte-flow__node')].find(
      (candidate) => candidate.dataset.id === nodeId,
    );
    return {
      width: element?.offsetWidth || fallback.width,
      height: element?.offsetHeight || fallback.height,
    };
  }

  function regionBounds(region: (typeof loopRegions)[number]): {
    left: number;
    top: number;
    width: number;
    height: number;
  } {
    const ids = [region.loopNodeId, ...region.bodyNodes];
    const members = viewNodes.filter((node) => ids.includes(node.id));
    const source =
      members.length > 0 ? members : viewNodes.filter((node) => node.id === region.loopNodeId);
    const boxes = source.map((node) => {
      const size = nodeSize(node.id);
      return {
        left: node.position.x,
        top: node.position.y,
        right: node.position.x + size.width,
        bottom: node.position.y + size.height,
      };
    });
    const left = Math.min(...boxes.map((box) => box.left));
    const top = Math.min(...boxes.map((box) => box.top));
    const right = Math.max(...boxes.map((box) => box.right));
    const bottom = Math.max(...boxes.map((box) => box.bottom));
    return {
      left: left - REGION_PADDING_X,
      top: top - REGION_PADDING_Y,
      width: right - left + REGION_PADDING_X * 2,
      height: bottom - top + REGION_PADDING_Y * 2,
    };
  }

  function selectLoopRegion(loopNodeId: string): void {
    session.selectLoopRegion(loopNodeId);
  }

  function toggleLoopRegion(region: (typeof loopRegions)[number]): void {
    session.collapseLoopRegion(region.loopNodeId, !region.collapsed);
  }
</script>

<div
  {@attach observeFlowNodeDimensions}
  data-slot="rule-flow-canvas"
  data-intent-focus={intentFocus ?? 'all'}
  class={cn(
    'relative h-full w-full overflow-hidden rounded-[var(--radius-panel)] border border-hairline bg-canvas',
    className,
  )}
>
  <SvelteFlow
    nodes={viewNodes}
    edges={viewEdges}
    {nodeTypes}
    edgeTypes={{ semantic: SemanticEdge }}
    isValidConnection={gate as unknown as IsValidConnection}
    onbeforeconnect={handleBeforeConnect}
    onconnect={handleConnect}
    onreconnect={handleReconnect}
    onnodedragstop={handleNodeDragStop}
    onnodeclick={handleNodeClick}
    onedgeclick={handleEdgeClick}
    onpaneclick={handlePaneClick}
    onselectionchange={handleSelectionChange}
    ondelete={handleDelete}
    elevateEdgesOnSelect={false}
    snapGrid={[16, 16]}
    minZoom={0.2}
    maxZoom={2}
    fitView
    fitViewOptions={{ padding: 0.3 }}
    defaultEdgeOptions={{ type: 'smoothstep' }}
    connectionLineType={SMOOTH_STEP_CONNECTION_LINE}
    ariaLabelConfig={CANVAS_ARIA_LABELS}
    proOptions={{ hideAttribution: true }}
    colorMode="system"
    class="flow-canvas"
  >
    <FlowTopBar
      {intentFocus}
      {nodeIds}
      flowEntryByIntent={entryByIntent}
      edges={semanticEdges}
      onFocusIntent={(intent: StandardIntent | null) => session.focusIntent(intent)}
      onAutoLayout={handleAutoLayout}
      {paletteOpen}
      onTogglePalette={() => (paletteOpen = !paletteOpen)}
    />
    {#if connectionRejectReason}
      <div class="pointer-events-none absolute inset-x-3 top-14 z-20 flex justify-center">
        <p
          class="border-danger/30 bg-surface text-danger max-w-full rounded border px-3 py-1.5 text-xs shadow-sm"
          role="status"
          aria-live="polite"
        >
          {connectionReasonText[connectionRejectReason]}
          <span class="ml-1 font-mono text-[10px] opacity-70">{connectionRejectReason}</span>
        </p>
      </div>
    {/if}
    {#key viewNodes.length}
      <ViewportSync />
    {/key}
    {#if paletteOpen}
      <NodePalette {session} onClose={() => (paletteOpen = false)} />
    {/if}
    <Background bgColor="var(--canvas)" patternColor="var(--hairline-strong)" gap={20} size={1.5} />
    {#each loopRegionViews as loopRegion (loopRegion.region.loopNodeId)}
      <ViewportPortal target="back">
        <LoopRegionOverlay
          region={loopRegion.region}
          {...loopRegion.bounds}
          selected={session.selection ===
            `loop-region:${encodeURIComponent(loopRegion.region.loopNodeId)}`}
          onSelect={() => selectLoopRegion(loopRegion.region.loopNodeId)}
          onToggle={() => toggleLoopRegion(loopRegion.region)}
        />
      </ViewportPortal>
    {/each}
    <Controls class="flow-controls" />
  </SvelteFlow>
</div>

<style>
  /* Svelte Flow 画布主题：使用既有 Ethereal token，不引入第二套样式。 */
  :global(.flow-canvas) {
    background: var(--canvas);
    font-family: var(--font-ui);
  }

  /* Svelte Flow 的 viewport 子层按 DOM 顺序渲染；固定语义层，避免 overlay 盖住图形。 */
  :global(.flow-canvas .svelte-flow__viewport-back) {
    z-index: 0;
    pointer-events: none;
  }

  :global(.flow-canvas .svelte-flow__edges),
  :global(.flow-canvas .svelte-flow__edge-labels) {
    z-index: 1;
  }

  :global(.flow-canvas .svelte-flow__nodes) {
    z-index: 2;
  }

  :global(.flow-canvas .svelte-flow__node) {
    z-index: 2 !important;
  }

  :global(.flow-canvas .svelte-flow__node[data-selected='true']) {
    z-index: 3 !important;
  }

  :global(.flow-canvas .svelte-flow__nodesselection) {
    z-index: 3;
  }

  :global(.flow-canvas .svelte-flow__edge-path),
  :global(.flow-canvas .svelte-flow__connection-path) {
    stroke: var(--lantern-strong);
    stroke-width: 2;
    stroke-linecap: round;
    stroke-linejoin: round;
    fill: none;
    transition:
      opacity var(--motion-fast) var(--motion-standard),
      stroke var(--motion-fast) var(--motion-standard),
      stroke-width var(--motion-fast) var(--motion-standard);
  }

  :global(.flow-canvas .flow-edge-dimmed) {
    opacity: 0.2;
  }

  :global(.flow-canvas .flow-edge-dimmed .svelte-flow__edge-path) {
    stroke: var(--ink-subtle);
  }

  :global(.flow-canvas .svelte-flow__edge:hover .svelte-flow__edge-path),
  :global(.flow-canvas .svelte-flow__edge.selected .svelte-flow__edge-path) {
    stroke: var(--lantern);
    stroke-width: 2.5;
  }

  :global(.flow-canvas .semantic-edge-control) {
    stroke: var(--lantern-strong);
    stroke-dasharray: 7 3;
  }

  :global(.flow-canvas .semantic-edge-binding) {
    stroke: var(--ink-muted);
    stroke-dasharray: 3 3;
  }

  :global(.flow-canvas .semantic-edge-branch) {
    stroke: var(--lantern-strong);
  }

  :global(.flow-canvas .semantic-edge-auxiliary) {
    opacity: 0.86;
  }

  :global(.flow-canvas .semantic-edge-lane-loop) {
    stroke: var(--lantern-strong);
  }

  :global(.flow-canvas .semantic-edge-loop-back) {
    stroke: var(--lantern-strong);
    stroke-dasharray: 8 4;
  }

  :global(.flow-canvas .semantic-edge-selected) {
    stroke: var(--lantern);
    stroke-width: 2.5;
  }

  :global(.flow-canvas .semantic-edge-label) {
    display: inline-flex;
    min-height: 18px;
    align-items: center;
    border: 1px solid var(--hairline-strong);
    border-radius: 4px;
    padding: 2px 5px;
    color: var(--ink-muted);
    background: var(--surface-panel);
    font-family: var(--font-mono);
    font-size: 9px;
    line-height: 1;
    box-shadow: var(--surface-control-shadow);
  }

  :global(.flow-canvas .semantic-edge-label-control) {
    border-color: color-mix(in oklab, var(--lantern-strong) 55%, var(--hairline-strong));
    color: var(--lantern-strong);
  }

  :global(.flow-canvas .semantic-edge-label-binding) {
    color: var(--ink-muted);
  }

  :global(.flow-canvas .svelte-flow__connection-path) {
    stroke: var(--lantern);
    stroke-dasharray: 5 4;
  }

  :global(.flow-canvas .svelte-flow__minimap) {
    background: var(--surface-panel);
    border: 1px solid var(--hairline);
    border-radius: var(--radius-md);
  }

  :global(.flow-canvas .svelte-flow__controls) {
    border: 1px solid var(--hairline);
    border-radius: var(--radius-md);
    overflow: hidden;
    box-shadow: var(--surface-control-shadow);
  }

  :global(.flow-canvas .svelte-flow__controls-button) {
    width: var(--density-control-md);
    height: var(--density-control-md);
    background: var(--surface-control);
    border-bottom: 1px solid var(--hairline);
    color: var(--ink-muted);
  }

  :global(.flow-canvas .svelte-flow__controls-button:hover) {
    background: var(--surface-2);
    color: var(--ink);
  }

  :global(.flow-canvas .svelte-flow__controls-button svg) {
    width: 15px;
    height: 15px;
    fill: currentColor;
  }

  @media (pointer: coarse) {
    :global(.flow-canvas .svelte-flow__controls-button) {
      width: var(--density-touch-target);
      height: var(--density-touch-target);
    }
  }
</style>

// src/features/rules/RuleFlowCanvas.tsx
//! 规则流程图画布：xyflow 受控容器。
//!
//! nodes/edges 全部来自 session 的 adapter 投影，画布不持有 core；
//! 连接、重连、删除都先过 connection gate，失败就不派发 —— 绝不写入无效语义。

import {
  Background,
  Controls,
  MiniMap,
  ReactFlow,
  ViewportPortal,
  useReactFlow,
  type Connection,
  type EdgeTypes,
  type NodeTypes,
  type OnSelectionChangeParams,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { cn } from '@/shared/utils';
import { useMessages } from '@/shared/i18n/messages';
import { useTheme } from '@/shared/theme/use-theme';
import {
  flowEntryByIntentFromDefinition,
  semanticEdgeFromConnection,
  validateConnection,
  type ConnectionRejectReason,
  type GateGraph,
} from './model/connection-gate';
import {
  loopRegionSelectionToken,
  parseEditorSelection,
  semanticHandleForUi,
  type FlowHandleDirection,
  type FlowViewEdge,
  type FlowViewNode,
  type LoopRegionView,
} from './model/flow-adapter';
import { selectFlowProjection } from './model/session';
import { useRuleEditorSession, useRuleEditorSessionStore } from './use-session';
import { RuleFlowNode } from './nodes/RuleFlowNode';
import { SemanticEdge } from './edges/SemanticEdge';
import { LoopRegionOverlay, type LoopRegionBounds } from './LoopRegionOverlay';
import { FlowTopBar } from './FlowTopBar';
import { NodePalette, usePaletteDrop } from './NodePalette';
import './rules-flow.css';

/** 节点数超过该阈值才渲染缩略图，小图不占画布空间。 */
const MINIMAP_NODE_THRESHOLD = 12;

/** 未实测到真实尺寸时的兜底，与 rules-flow.css 的卡片尺寸一致。 */
const NODE_FALLBACK = { width: 252, height: 142 };
const REGION_PADDING_X = 34;
const REGION_PADDING_Y = 38;

/** 拒绝提示的停留时长；不设自动消失会一直遮住画布顶部。 */
const REJECT_HINT_MS = 2600;

const nodeTypes: NodeTypes = {
  http: RuleFlowNode,
  js: RuleFlowNode,
  extract: RuleFlowNode,
  mapper: RuleFlowNode,
  merge: RuleFlowNode,
  condition: RuleFlowNode,
  loop: RuleFlowNode,
};

const edgeTypes: EdgeTypes = { semantic: SemanticEdge };

function rejectText(m: ReturnType<typeof useMessages>, reason: ConnectionRejectReason): string {
  switch (reason) {
    case 'missing-handle': {
      return m.rules_connect_reject_missing_handle();
    }
    case 'unknown-node': {
      return m.rules_connect_reject_unknown_node();
    }
    case 'unknown-handle': {
      return m.rules_connect_reject_unknown_handle();
    }
    case 'self-loop': {
      return m.rules_connect_reject_self_loop();
    }
    case 'incompatible-ports': {
      return m.rules_connect_reject_incompatible_ports();
    }
    case 'duplicate-edge': {
      return m.rules_connect_reject_duplicate_edge();
    }
    case 'entry-occupied': {
      return m.rules_connect_reject_entry_occupied();
    }
    case 'back-edge': {
      return m.rules_connect_reject_back_edge();
    }
    case 'loop-yield-occupied': {
      return m.rules_connect_reject_loop_yield_occupied();
    }
    case 'intent-mismatch': {
      return m.rules_connect_reject_intent_mismatch();
    }
  }
}

/** 从已渲染的 DOM 量节点实际尺寸；循环域边界要按真实高度算才不会切边。 */
function useNodeSizes(rootRef: React.RefObject<HTMLDivElement | null>) {
  const [epoch, setEpoch] = useState(0);

  useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    let disposed = false;
    let queued = false;
    const bump = () => {
      if (disposed || queued) return;
      queued = true;
      queueMicrotask(() => {
        queued = false;
        if (!disposed) setEpoch((value) => value + 1);
      });
    };

    const resizeObserver = new ResizeObserver(bump);
    const observeNodes = () => {
      resizeObserver.disconnect();
      for (const node of root.querySelectorAll<HTMLElement>('.react-flow__node')) {
        resizeObserver.observe(node);
      }
      bump();
    };
    const mutationObserver = new MutationObserver(observeNodes);
    mutationObserver.observe(root, { childList: true, subtree: true });
    observeNodes();

    return () => {
      disposed = true;
      resizeObserver.disconnect();
      mutationObserver.disconnect();
    };
  }, [rootRef]);

  return useCallback(
    (nodeId: string) => {
      const root = rootRef.current;
      if (!root || epoch === 0) return NODE_FALLBACK;
      const element = [...root.querySelectorAll<HTMLElement>('.react-flow__node')].find(
        (candidate) => candidate.dataset.id === nodeId,
      );
      return {
        width: element?.offsetWidth || NODE_FALLBACK.width,
        height: element?.offsetHeight || NODE_FALLBACK.height,
      };
    },
    [rootRef, epoch],
  );
}

export function RuleFlowCanvas({ className }: { className?: string }) {
  const m = useMessages();
  const { resolvedTheme } = useTheme();
  const store = useRuleEditorSessionStore();
  const rootRef = useRef<HTMLDivElement>(null);
  const nodeSize = useNodeSizes(rootRef);
  const [rejectReason, setRejectReason] = useState<ConnectionRejectReason | null>(null);
  const [paletteOpen, setPaletteOpen] = useState(false);
  const { fitView } = useReactFlow();
  const { onDragOver, onDrop } = usePaletteDrop();

  const projection = useRuleEditorSession(selectFlowProjection);
  const definition = useRuleEditorSession((state) => state.core.definition);
  const selection = useRuleEditorSession((state) => state.core.selection);
  const intentFocus = useRuleEditorSession((state) => state.core.intentFocus);

  /** 端口选择要把可视 handle 还原成 compiler 的 semantic handle。 */
  const selectPort = useCallback(
    (nodeId: string, direction: FlowHandleDirection, uiHandle: string) => {
      const node = selectFlowProjection(store.getState()).nodes.find(
        (candidate) => candidate.id === nodeId,
      );
      if (!node) return;
      store
        .getState()
        .selectPort(
          nodeId,
          direction,
          semanticHandleForUi(node.data.kind, node.data.config, uiHandle, direction),
        );
    },
    [store],
  );

  const nodes = useMemo<FlowViewNode[]>(
    () =>
      projection.nodes.map((node) => ({
        ...node,
        data: {
          ...node.data,
          onPortSelect: (direction: FlowHandleDirection, handle: string) =>
            selectPort(node.id, direction, handle),
        },
      })),
    [projection.nodes, selectPort],
  );

  const edges = useMemo<FlowViewEdge[]>(
    () => projection.edges.map((edge) => ({ ...edge, type: 'semantic' })),
    [projection.edges],
  );

  const entryByIntent = useMemo(() => flowEntryByIntentFromDefinition(definition), [definition]);

  const gateGraph = useMemo<GateGraph>(
    () => ({
      nodes: projection.nodes.map((node) => ({
        id: node.id,
        kind: node.data.kind,
        config: node.data.config,
      })),
      edges: projection.edges.map((edge) => edge.data.edge),
      focusEntry: intentFocus ? (entryByIntent[intentFocus] ?? null) : null,
    }),
    [projection.nodes, projection.edges, intentFocus, entryByIntent],
  );

  /** 校验并记录拒绝原因；`gate` 用于 isValidConnection，不落状态。 */
  const check = useCallback(
    (connection: Connection, graph: GateGraph = gateGraph): boolean => {
      const verdict = validateConnection(connection, graph);
      setRejectReason(verdict.ok ? null : verdict.reason);
      return verdict.ok;
    },
    [gateGraph],
  );

  // 拒绝提示自动消散，避免一直压在画布上。
  useEffect(() => {
    if (!rejectReason) return;
    const timer = setTimeout(() => setRejectReason(null), REJECT_HINT_MS);
    return () => clearTimeout(timer);
  }, [rejectReason]);

  const toSemanticEdge = useCallback(
    (connection: Connection) =>
      semanticEdgeFromConnection(
        connection,
        gateGraph.nodes.find((node) => node.id === connection.source),
        gateGraph.nodes.find((node) => node.id === connection.target),
      ),
    [gateGraph],
  );

  const deleteSelection = useCallback(
    (nodeIds: string[], edgeIds: string[]) => {
      if (nodeIds.length === 0 && edgeIds.length === 0) return;
      store.getState().deleteSelection(nodeIds, edgeIds);
    },
    [store],
  );

  // 快捷键：撤销 / 重做 / 删除。输入类元素内不拦截。
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      const { target } = event;
      if (
        target instanceof HTMLElement &&
        (target.tagName === 'INPUT' ||
          target.tagName === 'TEXTAREA' ||
          target.tagName === 'SELECT' ||
          target.isContentEditable)
      ) {
        return;
      }
      const modifier = event.metaKey || event.ctrlKey;
      const state = store.getState();
      if (modifier && !event.altKey && event.key.toLowerCase() === 'z') {
        event.preventDefault();
        if (event.shiftKey) state.redo();
        else state.undo();
        return;
      }
      if (modifier && !event.altKey && event.key.toLowerCase() === 'y') {
        event.preventDefault();
        state.redo();
        return;
      }
      if (event.key !== 'Delete' && event.key !== 'Backspace') return;
      const current = state.core.selection;
      if (!current) return;
      const parsed = parseEditorSelection(current);
      if (parsed.kind === 'edge') {
        event.preventDefault();
        deleteSelection([], [parsed.edgeId]);
      } else if (parsed.kind === 'node') {
        event.preventDefault();
        deleteSelection([parsed.nodeId], []);
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [store, deleteSelection]);

  // 意图焦点切换后把可达子图带进视野。
  useEffect(() => {
    if (!intentFocus) return;
    const timer = setTimeout(() => fitView({ padding: 0.3, duration: 240 }), 0);
    return () => clearTimeout(timer);
  }, [intentFocus, fitView]);

  const regionBounds = useCallback(
    (region: LoopRegionView): LoopRegionBounds => {
      const ids = new Set([region.loopNodeId, ...region.bodyNodes]);
      const members = nodes.filter((node) => ids.has(node.id));
      const source =
        members.length > 0 ? members : nodes.filter((node) => node.id === region.loopNodeId);
      if (source.length === 0) return { left: 0, top: 0, width: 0, height: 0 };
      const boxes = source.map((node) => {
        const size = nodeSize(node.id);
        return {
          left: node.position.x,
          top: node.position.y,
          right: node.position.x + size.width,
          bottom: node.position.y + size.height,
        };
      });
      const left = Math.min(...boxes.map((box) => box.left));
      const top = Math.min(...boxes.map((box) => box.top));
      const right = Math.max(...boxes.map((box) => box.right));
      const bottom = Math.max(...boxes.map((box) => box.bottom));
      return {
        left: left - REGION_PADDING_X,
        top: top - REGION_PADDING_Y,
        width: right - left + REGION_PADDING_X * 2,
        height: bottom - top + REGION_PADDING_Y * 2,
      };
    },
    [nodes, nodeSize],
  );

  const onSelectionChange = useCallback(
    ({ nodes: selectedNodes, edges: selectedEdges }: OnSelectionChangeParams) => {
      const state = store.getState();
      const [selectedEdge] = selectedEdges;
      if (selectedEdge) {
        if (state.core.selection !== `edge:${selectedEdge.id}`) state.selectEdge(selectedEdge.id);
        return;
      }
      const next = selectedNodes[0]?.id ?? null;
      if (state.core.selection !== next) state.selectNode(next);
    },
    [store],
  );

  return (
    <div
      ref={rootRef}
      data-slot="rule-flow-canvas"
      data-intent-focus={intentFocus ?? 'all'}
      className={cn('relative h-full w-full overflow-hidden bg-canvas', className)}
    >
      <ReactFlow
        nodes={nodes}
        edges={edges}
        nodeTypes={nodeTypes}
        edgeTypes={edgeTypes}
        isValidConnection={(connection) =>
          validateConnection(connection as Connection, gateGraph).ok
        }
        onConnect={(connection) => {
          if (!check(connection)) return;
          store.getState().connect(toSemanticEdge(connection));
        }}
        onReconnect={(oldEdge, connection) => {
          // 重连要排除正在替换的旧边，否则原位置会被误判成 duplicate。
          if (!check(connection, { ...gateGraph, excludeEdgeId: oldEdge.id })) return;
          const { edge: previous } = (oldEdge as FlowViewEdge).data;
          store.getState().reconnect(previous, toSemanticEdge(connection));
        }}
        onNodeDragStop={(_event, node) => {
          store.getState().moveNode(node.id, { x: node.position.x, y: node.position.y });
        }}
        onNodeClick={(_event, node) => store.getState().selectNode(node.id)}
        onEdgeClick={(_event, edge) => store.getState().selectEdge(edge.id)}
        onPaneClick={() => store.getState().selectNode(null)}
        onSelectionChange={onSelectionChange}
        onDelete={({ nodes: removedNodes, edges: removedEdges }) => {
          deleteSelection(
            removedNodes.map((node) => node.id),
            removedEdges.map((edge) => edge.id),
          );
        }}
        elevateEdgesOnSelect={false}
        snapGrid={[16, 16]}
        snapToGrid
        minZoom={0.2}
        maxZoom={2}
        fitView
        fitViewOptions={{ padding: 0.3 }}
        defaultEdgeOptions={{ type: 'smoothstep' }}
        connectionLineType={'smoothstep' as never}
        colorMode={resolvedTheme}
        proOptions={{ hideAttribution: true }}
        onDragOver={onDragOver}
        onDrop={onDrop}
        aria-label={m.rules_canvas_aria()}
      >
        <FlowTopBar paletteOpen={paletteOpen} onTogglePalette={() => setPaletteOpen((v) => !v)} />
        {paletteOpen ? <NodePalette onClose={() => setPaletteOpen(false)} /> : null}
        <Background gap={20} size={1.5} />
        {/* React 版 ViewportPortal 只有一个容器，层级靠 rules-flow.css 的 z-index。 */}
        {projection.loopRegions.map((region) => (
          <ViewportPortal key={region.loopNodeId}>
            <LoopRegionOverlay
              region={region}
              bounds={regionBounds(region)}
              selected={selection === loopRegionSelectionToken(region.loopNodeId)}
              onSelect={() => store.getState().selectLoopRegion(region.loopNodeId)}
              onToggle={() =>
                store.getState().collapseLoopRegion(region.loopNodeId, !region.collapsed)
              }
            />
          </ViewportPortal>
        ))}
        {nodes.length > MINIMAP_NODE_THRESHOLD ? (
          <MiniMap pannable zoomable nodeColor={() => 'var(--lantern-strong)'} />
        ) : null}
        <Controls showInteractive={false} />
      </ReactFlow>

      {rejectReason ? (
        <div className="pointer-events-none absolute inset-x-3 top-3 z-(--layer-popover) flex justify-center">
          <p
            role="status"
            aria-live="polite"
            className="max-w-full border border-danger/40 bg-surface-1 px-3 py-1.5 text-ui-sm text-danger"
          >
            {rejectText(m, rejectReason)}
            <span className="ml-1 font-mono text-[10px] opacity-70">{rejectReason}</span>
          </p>
        </div>
      ) : null}
    </div>
  );
}
